---
# String that is output when 'python --version' is run and is used as a variable to determine if the other tasks should be run
python_version_stdout: Python 3.6.3

# String that is used to determine file names to unarchive, paths to files, etc
python_full_version: Python-3.6.3

# Download URL pointing to the .tgz file containing the version of Python to install
python_download_url: https://www.python.org/ftp/python/3.6.3/Python-3.6.3.tgz

# String used for naming directory in /usr/local/{{ python_version_install_directory }}/ where Python version will be installed
python_version_install_directory: Python36

# Name of the python binary
python_binary_name: python3.6

# Name of pip binary
pip_binary_name: pip3.6

# Python dependency packages
packages: ["@development", openssl-devel, sqlite-devel, bzip2-devel, python-devel, httpd-devel, mod_ssl, openssl-perl, ncurses,
            ncurses-devel, gdbm, pyodbc, gdbm-devel, xz, xz-devel, tkinter, readline, readline-devel, tk, tk-devel, mysql,
            mysql-devel, mysql-libs, gcc, unixODBC, unixODBC-devel, memcached, openldap, openldap-devel, libjpeg-turbo,
            libjpeg-turbo-devel, libpng, zlib, zlib-devel, giflib, python-imaging, python-imaging-devel, freetds, freetds-devel,
            libxml2-devel, libffi-devel]
